### ISSUE TITLE
Error with emacs 27.1

### ISSUE THREAD

**Issue by magnetophon** [rukano/emacs-faust-mode#15]
When I try to use faust mode on emacs 27.1, I get:
```
Eager macro-expansion failure: (error "Invalid rx ‘any’ range: ^-+")
rx--string-to-intervals: Invalid rx ‘any’ range: ^-+
```

**Comment by magnetophon** [comment]
When I change [this line](https://github.com/rukano/emacs-faust-mode/blob/master/faust-mode.el#L184):
```lisp
(defconst faust-regexp-faust-operator (rx (any ",'@:*/%^-+|&~>=<!")))
```
to
```lisp
(defconst faust-regexp-faust-operator (rx (any ",'@:*/%^|&~>=<!")))
```
the error goes away and I get (incomplete) highlighting again.

**Comment by nbfalcon** [comment]
```emacs-lisp
(rx (any ?- ",'@:*/%^+|&~>=<!"))
(rx (any (?, ?' ?@ ?: ?* ?/ ?% ?^ ?+ ?- ?| ?& ?~ ?> ?= ?< ?!)))
```
Either of these should probably work (I think I prefer the latter). Not tested.

**Comment by magnetophon** [comment]
@nbfalcon Thanks!

That second version gives me an error: ``rx requires a string or...``
I'm rebuilding my doom config using the first version now, and will do a PR if it works.
How shall I credit you?

**Comment by nbfalcon** [comment]
@magnetophon the second version way indeed wrong; fixed it (extra parens in any). As for crediting, mentioning this issue is enough for me. Glad that I could help :)

**Comment by agraef** [comment]
Yep, I'm getting exactly the same on Manjaro, using faust-mode.el included in the community faust package.
